### ISSUE TITLE
Can i call crowdstrike spotlight api?

### ISSUE THREAD

**Issue by EnricoMucelli** [CrowdStrike/rusty-falcon#75]
Can somone show me how to call crowdstrike spotlight api?

**Comment by isimluk** [comment]
Hello @EnricoMucelli,

You should be able to call CrowdStrike Spotlight API using rusty-falcon. I can attempt to write an exemplary use-case.

What requirements do you have? Do you just want to download known vulnerabilities matching user provided filter? Or are you looking for something else.

**Comment by EnricoMucelli** [comment]
hi @isimluk  thank you for the response!
yes i would like to do that

**Comment by isimluk** [comment]
Hello @EnricoMucelli,

Sorry it took me so long to provide an initial sample on how to use spotlight API. Please let me know if I can explain the code better, or if there is anything else I could add/change.

Thank You.

**Comment by ErtyDess** [comment]
Thank you man, very appreciated!
